---

- name: Check if packages need to be autoremoved
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False

- name: Autoremove unused packages
  command: apt-get -y autoremove
  when: "'packages will be REMOVED' in check_autoremove.stdout"

- name: Apt update followed by apt upgrade
  apt: upgrade=yes update_cache=yes

- name: Install rsync for ntp
  apt: name=rsync state=present

- name: Install apache2 for monit
  apt: name=apache2 state=present


- name: Install git for Zabbix agent
  apt: name=git state=present

- name: Install ttf-dejavu-core for Zabbix frontend
  apt: name=ttf-dejavu-core state=present
