---

- name: common | Download Zabbix sources
  command: wget repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb

- name: common | Install Zabbix package v2.2
  command: dpkg -i zabbix-release_2.2-1+trusty_all.deb

- name: common | Remove downloaded Zabbix package
  file: name=zabbix-release_2.2-1+trusty_all.deb state=absent

- name: common | Install mysql client
  apt: name={{ item }} state=present
  with_items:
    - zabbix-agent
    - mysql-client
#- name: common | Install pre dependency
#  apt:
#     pkg={{ item }}
#     state=present
#  with_items:
#     - python-pip
#     - libcurl3-gnutls
#     - update-notifier-common

#- name: common | Install python
#  apt: name={{ item }} state=present
#  with_items:
#     - python-dev
#     - python-pip
#     - libmysqlclient-dev

#- name: common | Install mysqldb module
#  pip: name=MySQL-python state=present

#- name: common | Install zabbix-api module
#  pip: name=zabbix-api state=present

#- name: Common | Install zabbix-server-mysql
#  apt: name=zabbix-server-mysql state=present
