---

- name: Download Zabbix sources
  command: wget -q repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb

- name: Install Zabbix package v2.2
  command: dpkg -i zabbix-release_2.2-1+trusty_all.deb

- name: Remove downloaded Zabbix package
  file: name=zabbix-release_2.2-1+trusty_all.deb state=absent

- name: Install Zabbix agent and Zabbix frontend-php
  apt: name={{ item }} state=present
  with_items:
     - zabbix-agent
     - zabbix-frontend-php

- name: Rsync zabbix_agentd.conf to /etc/zabbix
  synchronize: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
