---

- name: Download Zabbix sources
  command: wget repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+precise_all.deb

- name: Install Zabbix agent 2.2
  command: dpkg -i zabbix-release_2.2-1+precise_all.deb

- name: Remove downloaded Zabbix package
  file: name=zabbix-release_2.2-1+precise_all.deb state=absent

- name: Install Zabbix frontend-php
  apt: name=zabbix-frontend-php state=present
