---
- include: common.yml
  when: zabbix_server_front_install or zabbix_server_install or zabbix_server_proxy_install or zabbix_agent_install

- include: frontend.yml
  when: zabbix_server_front_install

#- name: Rsync zabbix_agentd.conf to /etc/zabbix
#  synchronize: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf


- name: zabbix_agent | Deploy zabbix_agentd.conf file
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Server=" line="Server={{ zabbix_agent_Server }}"
- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^ServerActive=" line="ServerActive={{ zabbix_agent_Server }}"
- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Hostname=" line="Hostname=zabbix-agent"
