---

#- name: Download Zabbix sources
#  command: wget repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+precise_all.deb

#- name: Install Zabbix package v2.2
#  command: dpkg -i zabbix-release_2.2-1+precise_all.deb

#- name: Remove downloaded Zabbix package
#  file: name=zabbix-release_2.2-1+precise_all.deb state=absent

- name: Install Zabbix MySQL server
  apt: name={{ item }} state=present
  with_items:
     - zabbix-server-mysql
     - php5-mysql

- name: Set custom hostname
  hostname: name=zabbix-server

- name: Edit zabbix_server.conf
  lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp="^# DBPassword=" line=DBPassword=1111

- name: Unpack mysql data for further importing
  command: chdir=/usr/share/zabbix-server-mysql/ {{ item }}
  with_items:
     - gunzip -kf /usr/share/zabbix-server-mysql/data.sql.gz
     - gunzip -kf /usr/share/zabbix-server-mysql/schema.sql.gz 
     - gunzip -kf /usr/share/zabbix-server-mysql/images.sql.gz 

- name: Add user zabbix to MySQL
  mysql_user: password=1111 name=zabbix priv=*.*:ALL,GRANT state=present

- name: Create MySQL database for zabbix
  mysql_db: name=zabbix state=present

- name: Import schemas into database
  command: chdir=/usr/share/zabbix-server-mysql/ {{ item }}
  with_items:
     - echo 1111|sudo -S /usr/bin/mysql -u zabbix -p < schema.sql
     - echo 1111|sudo -S /usr/bin/mysql -u zabbix -p < images.sql
     - echo 1111|sudo -S /usr/bin/mysql -u zabbix -p < data.sql

- name: Copy default zabbix.conf.php to /etc/zabbix
  synchronize: src=zabbix.conf.php dest=/etc/zabbix/zabbix.conf.php

- name: Edit apache php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^post_max_size" line="post_max_size = 16M"

- lineinfile: dest=/etc/php5/apache2/php.ini regexp="^max_execution_time" line="max_execution_time = 300"
- lineinfile: dest=/etc/php5/apache2/php.ini regexp="^max_input_time" line="max_input_time = 300"
- lineinfile: dest=/etc/php5/apache2/php.ini regexp="^[Date]" line="[Date] \ndate.timezone = \"Europe/Minsk\""

- name: Copy the example apache config to conf-available/
  command: cp /usr/share/doc/zabbix-frontend-php/examples/apache.conf /etc/apache2/conf-available/zabbix.conf 

- name: Fix apache not determening server
  lineinfile: dest=/etc/apache2/apache2.conf line="ServerName 127.0.0.1"

- name: Make Zabbix and Apache work together
  apache2_module: name=alias state=present

- command: a2enconf zabbix.conf
- service: name=apache2 state=restarted
- lineinfile: dest=/etc/default/zabbix-server regexp="^START=" line="START=yes"
- service: name=zabbix-server state=restarted
