---

- name: mysql | Install mysql-server
  apt: name=mysql-server state=present

- name: mysql | Create Zabbix mysql database
  mysql_db:
    name: "{{zabbix_server_db_name}}"
    state: present
  notify: restart apache2
  tags: mysql_server

- name: mysql | Create zabbix mysql user
  mysql_user:
    name: "{{zabbix_server_db_user}}"
    password: "{{zabbix_server_db_pass}}"
    priv: "{{zabbix_server_db_name}}.*:ALL,GRANT"
    state: present
    host: "{{zabbix_server_db_host}}"
  tags: mysql_server

- name: mysql | Create remote zabbix user
  mysql_user:
    name: "{{zabbix_server_db_user}}"
    password: "{{zabbix_server_db_pass}}"
    priv: "{{zabbix_server_db_name}}.*:ALL,GRANT"
    state: present
    host: "%"
  tags: mysql_server

- name: mysql | Create remote zabbix user (second try)
  mysql_user:
    name: "{{zabbix_server_db_user}}"
    password: "{{zabbix_server_db_pass}}"
    priv: "{{zabbix_server_db_name}}.*:ALL,GRANT"
    state: present
    host: "192.168.33.11"
  tags: mysql_server

- name: mysql | Change my.cnf
  template:
     src="my.cnf.j2"
     dest="/etc/mysql/my.cnf"
     owner=root
     group=root
     mode=0644
