---

- name: zabbix_server | Install Zabbix Server
  apt: name=zabbix-server-mysql state=present force=yes

- name: Unpack mysql data for further importing
  command: chdir=/usr/share/zabbix-server-mysql/ {{ item }}
  with_items:
     - gunzip -kf /usr/share/zabbix-server-mysql/data.sql.gz
     - gunzip -kf /usr/share/zabbix-server-mysql/schema.sql.gz
     - gunzip -kf /usr/share/zabbix-server-mysql/images.sql.gz

- name: zabbix_server | Zabbix server conf file
  template:
     src=server/zabbix_server.conf.j2
     dest=/etc/zabbix/zabbix_server.conf
     owner=zabbix
     group=zabbix
     mode=600
  notify: restart zabbix_server

- name: zabbix_server | Add ServerName to apache config to avoid determination error
  lineinfile: dest=/etc/apache2/apache2.conf line="ServerName 127.0.0.1"

- name: zabbix_server | Set up database to START
  lineinfile: dest=/etc/default/zabbix-server regexp="^START" line="START=yes"

- name: zabbix_server | Backup default service file
  command: mv -v /etc/init.d/zabbix-server /etc/init.d/zabbix-server.orig

- name: zabbix_server | Replace service file with WORKING one
  synchronize: src=zabbix-server dest=/etc/init.d/zabbix-server



