# file: mysql/tasks/configure.yml

- name: MySQL | Update the my.cnf
  template:
    src: etc_mysql_my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mysql

- name: install gunzip if necessary
  apt: name=gunzip state=present

- name: Unpack mysql data for further importing
  command: /bin/gunzip *.gz chdir=/usr/share/zabbix-server-mysql/ 

- name: Add user zabbix to MySQL
  mysql_user: password=zabbix name=zabbix priv=*.*:ALL,GRANT state=present

- name: Create MySQL database for zabbix
  mysql_db: name=zabbix state=present

- name: Import schemas into database
  command: /usr/bin/mysql -u zabbix -p zabbix < schema.sql
- name: Import schemas into database
  command: /usr/bin/mysql -u zabbix -p zabbix < images.sql
- name: Import schemas into database
  command: /usr/bin/mysql -u zabbix -p zabbix < data.sql

