---

- name: Download Zabbix sources
  command: wget repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb

- name: Install Zabbix package v2.2
  command: dpkg -i zabbix-release_2.2-1+precise_all.deb

- name: Remove downloaded Zabbix package
  file: name=zabbix-release_2.2-1+precise_all.deb state=absent

- name: Install zabbix-server-mysql and zabbix-frontend-php
  apt: name={{ item }} state=present
  with_items:
     - zabbix-server-mysql
     - zabbix-frontend-php

- name: Set "true" in /etc/dbconfig-common/config
  lineinfile: dest=/etc/dbconfig-common/config regexp="^dbc_remote_questions_default=" line="dbc_remote_questions_default=\'true\'"

- name: Copy zabbix apache configuration file in to apache2 directory
  command: cp /etc/zabbix/apache.conf /etc/apache2/sites-enabled/zabbix.conf

- name: Change the following line to right time zone
  lineinfile: dest=/etc/apache2/sites-enabled/zabbix.conf regexp="^#php_value data_timezone" line="php_value date.timezone Europe/Minsk"

