---

- name: Check if packages need to be autoremoved
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False

- name: Autoremove unused packages
  command: apt-get -y autoremove
  when: "'packages will be REMOVED' in check_autoremove.stdout"

#- name: Apt update followed by apt upgrade
#  apt: upgrade=yes update_cache=yes

- name: Apt-key update
  command: apt-key update -y

- name: Install rsync for ntp
  apt: name={{ item }} state=present
  with_items:
    - vim
    - git
    - ttf-dejavu-core

